server:
  port: 1010
  servlet:
    context-path: /identity
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/identity_service
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
jwt:
  signerKey: "q8ibtqQsPE8HoWkgRezRmmFpttOb1viAEFeIdoOL3o2e6pbK1AUXaMct+/7tOZ2h4VKmNFutOu5A4S7L9+jKHg=="